export const metadata = {
  title: 'IPS MIGUEL ARCANGEL',
  description: 'Generated by Next.js',
  icons:{
    icon: ['/favicon.ico?=v4']
  }
  
}
import {  } from "../styles/main.css";

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
